### ISSUE TITLE
Can we have # for decimal?

### ISSUE THREAD

**Issue by robzed** [mattsteeldue/vforth-next#3]
We can have %1010 for binary numbers and $20 for hex numbers.
Is it possible to support # for decimal, such as #128 or #-30?

This is documented here under https://forth-standard.org/standard/usage - see section 3.4.1.3 Text interpreter input number conversion

**Comment by mattsteeldue** [comment]
planned on build 20240101

**Comment by mattsteeldue** [comment]
![image](https://github.com/mattsteeldue/vforth-next/assets/44555162/679482a8-0ef6-4612-a79b-2485f14714d9)

**Comment by mattsteeldue** [comment]
Also negative numbers works  #-10   $-10  %-10
